# Generated by Django 3.2.9 on 2021-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_d', models.CharField(max_length=255)),
                ('kch', models.CharField(max_length=255)),
                ('kxh', models.CharField(max_length=255)),
                ('kcm', models.CharField(max_length=255)),
                ('zxjxjhh', models.CharField(max_length=255)),
                ('skjs', models.CharField(max_length=255)),
                ('kkxy', models.CharField(max_length=255)),
                ('classWeek', models.CharField(max_length=255)),
                ('classDay', models.IntegerField()),
                ('classSessions', models.IntegerField()),
                ('continuingSession', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('kch', models.CharField(max_length=255)),
                ('kxh', models.CharField(max_length=255)),
                ('kcm', models.CharField(max_length=255)),
                ('zxjxjhh', models.CharField(max_length=255)),
                ('skjs', models.CharField(max_length=255)),
                ('kkxy', models.CharField(max_length=255)),
                ('classWeek', models.CharField(max_length=255)),
                ('classDay', models.IntegerField()),
                ('classSessions', models.IntegerField()),
                ('continuingSession', models.IntegerField()),
            ],
        ),
    ]
