# Generated by Django 3.2.9 on 2021-11-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentCourses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='kkxy',
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='classWeek',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='course_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='kch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='kcm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='kxh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='skjs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='zxjxjhh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
